/** Shared constants — safe to import from client components */

export const STATE_CODES: Record<string, string> = {
  Abia: "ABI",
  Adamawa: "ADA",
  "Akwa Ibom": "AKW",
  Anambra: "ANA",
  Bauchi: "BAU",
  Bayelsa: "BAY",
  Benue: "BEN",
  Borno: "BOR",
  "Cross River": "CRS",
  Delta: "DEL",
  Ebonyi: "EBO",
  Edo: "EDO",
  Ekiti: "EKI",
  Enugu: "ENU",
  Gombe: "GOM",
  Imo: "IMO",
  Jigawa: "JIG",
  Kaduna: "KAD",
  Kano: "KAN",
  Katsina: "KAT",
  Kebbi: "KEB",
  Kogi: "KOG",
  Kwara: "KWA",
  Lagos: "LAG",
  Nasarawa: "NAS",
  Niger: "NIG",
  Ogun: "OGU",
  Ondo: "OND",
  Osun: "OSU",
  Oyo: "OYO",
  Plateau: "PLA",
  Rivers: "RIV",
  Sokoto: "SOK",
  Taraba: "TAR",
  Yobe: "YOB",
  Zamfara: "ZAM",
  "Federal Capital Territory": "FCT",
};

export const NIGERIAN_STATES = Object.keys(STATE_CODES);
